# Generated by Django 5.2.6 on 2025-11-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteadminprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrganizationLeaderProfile',
        ),
        migrations.DeleteModel(
            name='SiteAdminProfile',
        ),
    ]
