# Generated by Django 5.2.6 on 2025-11-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_siteadminprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/pictures/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
