# Generated by Django 5.2.6 on 2025-11-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_room_alter_event_host_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='administrators',
        ),
    ]
