# Generated by Django 5.2.6 on 2025-11-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='username',
        ),
    ]
