# Generated by Django 5.2.6 on 2025-11-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_organization_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
