# Generated by Django 5.2.6 on 2025-11-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_instagram_organization_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='discord',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='slack',
            field=models.URLField(blank=True),
        ),
    ]
