# Generated by Django 5.2.6 on 2025-11-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_discord_organization_slack'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
