# Generated by Django 5.2.6 on 2025-12-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_email_organization_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.CharField(default='club-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
