# Generated by Django 5.2.6 on 2025-11-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Hashed organization password', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(blank=True, help_text='Organization login username', max_length=150, null=True, unique=True),
        ),
    ]
